import { Category, Product } from './types';

/**
 * PRODUCT CATALOG
 * 
 * IMAGE INSTRUCTIONS:
 * Ensure your local images are placed in the public/ folder matching these paths:
 * - public/images/fashion/ (Maps to Clothes category)
 * - public/images/accessories/
 * - public/images/home/ (Maps to Miscellaneous category)
 * - public/images/art/
 * - public/images/banners/ (For homepage categories)
 * 
 * File extensions must be .png (or update the strings below).
 */

export const MOCK_PRODUCTS: Product[] = [
  // --- CLOTHES (Formerly Fashion) ---
  {
    id: 'f1',
    name: 'Royal Habesha Kemis',
    price: 280,
    currency: '€',
    category: Category.CLOTHES,
    description: 'Exquisite handwoven cotton dress with gold-thread Tibeb embroidery.',
    detailedHistory: 'Worn for weddings and Timkat festivals, this Kemis represents the pinnacle of Ethiopian weaving (Shemma). The gold threads are woven into the cotton using a technique passed down for centuries.',
    imageUrl: '/images/fashion/royal-habesha-kemis.png',
    inStock: true,
  },
  {
    id: 'f2',
    name: 'Men’s Traditional Telet Suit',
    price: 150,
    currency: '€',
    category: Category.CLOTHES,
    description: 'Crisp white cotton tunic and trousers with national tricolor trim.',
    detailedHistory: 'A staple for Ethiopian men during holidays. The pure white cotton symbolizes purity, while the clean lines offer timeless elegance suitable for both church services and modern gatherings.',
    imageUrl: '/images/fashion/mens-telet-suit.png',
    inStock: true,
  },
  {
    id: 'f3',
    name: 'Handwoven Netela Scarf',
    price: 45,
    currency: '€',
    category: Category.CLOTHES,
    description: 'Lightweight, gauze-like cotton scarf with colorful border.',
    detailedHistory: 'The Netela is worn daily by Ethiopian women. It is incredibly versatile, used as a headwrap, a shawl, or a sash. The intricate border pattern (Tibeb) indicates the wearer’s region.',
    imageUrl: '/images/fashion/netela-scarf.png',
    inStock: true,
  },
  {
    id: 'f4',
    name: 'Heavy Cotton Gabi',
    price: 85,
    currency: '€',
    category: Category.CLOTHES,
    description: 'Thick, four-layer cotton blanket wrap for cold evenings.',
    detailedHistory: 'While the Netela is for the day, the Gabi is for the cold highland nights. It is essentially a wearable blanket, woven with thicker cotton threads to trap heat.',
    imageUrl: '/images/fashion/cotton-gabi.png',
    inStock: true,
  },
  {
    id: 'f5',
    name: 'Modern Tibeb Bomber Jacket',
    price: 120,
    currency: '€',
    category: Category.CLOTHES,
    description: 'Urban streetwear fused with traditional weaving patterns.',
    detailedHistory: 'Designed by young Addis Ababa creatives, this jacket features authentic Tibeb strips sewn onto high-quality modern fabrics, bridging the gap between heritage and hip-hop culture.',
    imageUrl: '/images/fashion/tibeb-bomber.png',
    inStock: true,
  },
  {
    id: 'f6',
    name: 'Wollo Raya Dress',
    price: 220,
    currency: '€',
    category: Category.CLOTHES,
    description: 'Distinctive black and gold dress style from the Wollo region.',
    detailedHistory: 'Unlike the typical white Shemma, the Raya style is bold and colorful, often accessorized with heavy jewelry. It reflects the vibrant culture of Northern Ethiopia.',
    imageUrl: '/images/fashion/wollo-raya-dress.png',
    inStock: false,
  },

  // --- ACCESSORIES ---
  {
    id: 'a1',
    name: 'Axumite Silver Cross Pendant',
    price: 95,
    currency: '€',
    category: Category.ACCESSORIES,
    description: 'Intricate filigree silver cross inspired by the Axum empire.',
    detailedHistory: 'Lost-wax casting creates these delicate masterpieces. Each region in Ethiopia has a distinct cross style; this one features the flared arms typical of the Tigray region.',
    imageUrl: '/images/accessories/axumite-cross.png',
    inStock: true,
  },
  {
    id: 'a2',
    name: 'Lalibela Processional Cross (Replica)',
    price: 180,
    currency: '€',
    category: Category.ACCESSORIES,
    description: 'Large, hand-held brass cross with complex lattice patterns.',
    detailedHistory: 'Used by priests during processions, these crosses symbolize the order of the universe. The "Birds of Peace" motif is often hidden within the geometric lattice.',
    imageUrl: '/images/accessories/lalibela-cross.png',
    inStock: true,
  },
  {
    id: 'a3',
    name: 'Omo Valley Beaded Necklace',
    price: 55,
    currency: '€',
    category: Category.ACCESSORIES,
    description: 'Vibrant, multi-strand glass bead necklace.',
    detailedHistory: 'Crafted by the women of the Omo Valley tribes. The colors and patterns often signify marital status, age, and social standing within the community.',
    imageUrl: '/images/accessories/omo-beads.png',
    inStock: true,
  },
  {
    id: 'a4',
    name: 'Addis Leather Tote',
    price: 140,
    currency: '€',
    category: Category.ACCESSORIES,
    description: 'Premium Ethiopian highland sheepskin leather bag.',
    detailedHistory: 'Ethiopian leather is prized globally for its softness and durability. This bag is tanned using vegetable dyes in a sustainable facility near Addis Ababa.',
    imageUrl: '/images/accessories/leather-tote.png',
    inStock: true,
  },

  // --- MISCELLANEOUS PRODUCTS (Formerly Home & Coffee) ---
  {
    id: 'h1',
    name: 'Traditional Jebena Pot',
    price: 45,
    currency: '€',
    category: Category.MISC,
    description: 'Black clay pottery used for brewing traditional coffee.',
    detailedHistory: 'The Jebena is the centerpiece of the coffee ceremony. Its spherical bottom allows grounds to settle, while the long neck pours clear, strong coffee.',
    imageUrl: '/images/home/jebena-pot.png',
    inStock: true,
  },
  {
    id: 'h2',
    name: 'Sini Coffee Cups (Set of 6)',
    price: 35,
    currency: '€',
    category: Category.MISC,
    description: 'Small, handleless porcelain cups with traditional motifs.',
    detailedHistory: 'Coffee (Buna) is always drunk in company. These small cups ensure that the coffee is consumed quickly while hot, usually in three rounds: Abol, Tona, and Baraka.',
    imageUrl: '/images/home/sini-cups.png',
    inStock: true,
  },
  {
    id: 'h3',
    name: 'Harar Mesob Basket',
    price: 110,
    currency: '€',
    category: Category.MISC,
    description: 'Large, colorful woven basket table with lid.',
    detailedHistory: 'The Mesob serves as a dining table. Friends and family gather around it to share a meal from a single platter, symbolizing unity and brotherhood.',
    imageUrl: '/images/home/harar-mesob.png',
    inStock: true,
  },
  {
    id: 'h4',
    name: 'Yirgacheffe Coffee Beans (1kg)',
    price: 38,
    currency: '€',
    category: Category.MISC,
    description: 'Premium single-origin beans, floral and citrus notes.',
    detailedHistory: 'Yirgacheffe is considered the birthplace of coffee. These beans are washed and sun-dried, offering a light, tea-like body with distinct jasmine aromas.',
    imageUrl: '/images/home/yirgacheffe-beans.png',
    inStock: true,
  },
  {
    id: 'h5',
    name: 'Frankincense & Myrrh Gift Set',
    price: 28,
    currency: '€',
    category: Category.MISC,
    description: 'High-grade resin incense from the Tigray region.',
    detailedHistory: 'Incense is burned during coffee ceremonies to purify the air. This set includes a traditional clay burner and resin harvested from Boswellia trees.',
    imageUrl: '/images/home/incense-set.png',
    inStock: true,
  },

  // --- ART ---
  {
    id: 'ar1',
    name: 'St. George Slaying the Dragon',
    price: 450,
    currency: '€',
    category: Category.ART,
    description: 'Hand-painted icon on goatskin vellum.',
    detailedHistory: 'St. George is the patron saint of Ethiopia. This piece follows the Second Gondarine style, characterized by bold lines and expressive eyes.',
    imageUrl: '/images/art/st-george-icon.png',
    inStock: true,
  },
  {
    id: 'ar2',
    name: 'Solomon & Sheba Triptych',
    price: 380,
    currency: '€',
    category: Category.ART,
    description: 'Three-panel wooden icon telling the Kebra Nagast story.',
    detailedHistory: 'Depicts the legendary meeting of King Solomon and the Queen of Sheba, the foundational myth of the Solomonic dynasty in Ethiopia.',
    imageUrl: '/images/art/solomon-sheba.png',
    inStock: true,
  },
  {
    id: 'ar3',
    name: 'Ethiopian Angel Heads',
    price: 180,
    currency: '€',
    category: Category.ART,
    description: 'Canvas painting of the famous ceiling angels of Debre Berhan Selassie.',
    detailedHistory: 'One of the most recognizable images in Ethiopian art. The winged heads represent the omnipresence of God, watching from the heavens.',
    imageUrl: '/images/art/angel-heads.png',
    inStock: true,
  },
  {
    id: 'ar4',
    name: 'Abstract Addis Jazz',
    price: 550,
    currency: '€',
    category: Category.ART,
    description: 'Contemporary acrylic painting by emerging Addis artist.',
    detailedHistory: 'Inspired by the Ethio-Jazz movement of the 1970s (Mulatu Astatke), this piece uses vibrant colors to capture the chaotic energy of Addis Ababa nightlife.',
    imageUrl: '/images/art/addis-jazz-art.png',
    inStock: true,
  },
];